#!/bin/bash
rm /var/lib/tor/other_hidden_service/hostname
service tor start;
cp /var/lib/tor/other_hidden_service/hostname /hostname
chmod -R  777  /hostname
proxychains python3 /app/chat_server.py;


