#!/bin/bash
clear
docker-compose exec torchatpublic proxychains   netcat -vz  $(./command/hostname) 9052 
docker-compose exec torchatpublic proxychains   netcat -vz  $(./command/hostname) 9052 
docker-compose exec torchatpublic proxychains   netcat -v  $(./command/hostname) 9052 
